/*
 * This file is generated by jOOQ.
*/
package test.boot.entity.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RedisNode implements Serializable {

    private static final long serialVersionUID = -701275449;

    private Integer id;
    private String  host;
    private Integer port;
    private Integer cId;

    public RedisNode() {}

    public RedisNode(RedisNode value) {
        this.id = value.id;
        this.host = value.host;
        this.port = value.port;
        this.cId = value.cId;
    }

    public RedisNode(
        Integer id,
        String  host,
        Integer port,
        Integer cId
    ) {
        this.id = id;
        this.host = host;
        this.port = port;
        this.cId = cId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getHost() {
        return this.host;
    }

    public void setHost(String host) {
        this.host = host;
    }

    public Integer getPort() {
        return this.port;
    }

    public void setPort(Integer port) {
        this.port = port;
    }

    public Integer getCId() {
        return this.cId;
    }

    public void setCId(Integer cId) {
        this.cId = cId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RedisNode (");

        sb.append(id);
        sb.append(", ").append(host);
        sb.append(", ").append(port);
        sb.append(", ").append(cId);

        sb.append(")");
        return sb.toString();
    }
}
