/*
 * This file is generated by jOOQ.
*/
package test.boot.entity;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_1D194736_C69A_4659_A0C2_D18FE5E91A9B</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_1D194736_C69A_4659_A0C2_D18FE5E91A9B = new SequenceImpl<Long>("SYSTEM_SEQUENCE_1D194736_C69A_4659_A0C2_D18FE5E91A9B", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_25A3DF42_66BE_4FAD_82FA_DC938C2B0094</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_25A3DF42_66BE_4FAD_82FA_DC938C2B0094 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_25A3DF42_66BE_4FAD_82FA_DC938C2B0094", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_C59BD5C2_4793_4348_96DD_48FA120B8E95</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_C59BD5C2_4793_4348_96DD_48FA120B8E95 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_C59BD5C2_4793_4348_96DD_48FA120B8E95", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
