/*
 * This file is generated by jOOQ.
*/
package test.boot.entity;


import javax.annotation.Generated;

import test.boot.entity.tables.RedisCollection;
import test.boot.entity.tables.RedisConnection;
import test.boot.entity.tables.RedisNode;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.REDIS_CONNECTION</code>.
     */
    public static final RedisConnection REDIS_CONNECTION = test.boot.entity.tables.RedisConnection.REDIS_CONNECTION;

    /**
     * The table <code>PUBLIC.REDIS_COLLECTION</code>.
     */
    public static final RedisCollection REDIS_COLLECTION = test.boot.entity.tables.RedisCollection.REDIS_COLLECTION;

    /**
     * The table <code>PUBLIC.REDIS_NODE</code>.
     */
    public static final RedisNode REDIS_NODE = test.boot.entity.tables.RedisNode.REDIS_NODE;
}
