/*
 * This file is generated by jOOQ.
*/
package test.boot.entity.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import test.boot.entity.tables.RedisCollection;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RedisCollectionRecord extends UpdatableRecordImpl<RedisCollectionRecord> implements Record3<Integer, String, Integer> {

    private static final long serialVersionUID = 1719965830;

    /**
     * Setter for <code>PUBLIC.REDIS_COLLECTION.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.REDIS_COLLECTION.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.REDIS_COLLECTION.COMMAND</code>.
     */
    public void setCommand(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.REDIS_COLLECTION.COMMAND</code>.
     */
    public String getCommand() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.REDIS_COLLECTION.CONN_ID</code>.
     */
    public void setConnId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.REDIS_COLLECTION.CONN_ID</code>.
     */
    public Integer getConnId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return RedisCollection.REDIS_COLLECTION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return RedisCollection.REDIS_COLLECTION.COMMAND;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return RedisCollection.REDIS_COLLECTION.CONN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCommand();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getConnId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RedisCollectionRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RedisCollectionRecord value2(String value) {
        setCommand(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RedisCollectionRecord value3(Integer value) {
        setConnId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RedisCollectionRecord values(Integer value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RedisCollectionRecord
     */
    public RedisCollectionRecord() {
        super(RedisCollection.REDIS_COLLECTION);
    }

    /**
     * Create a detached, initialised RedisCollectionRecord
     */
    public RedisCollectionRecord(Integer id, String command, Integer connId) {
        super(RedisCollection.REDIS_COLLECTION);

        set(0, id);
        set(1, command);
        set(2, connId);
    }
}
